#!/usr/bin/env ruby
require_relative '../application'

instance = SCNR::Application.spawn( :instance )

instance.run(
    url:    'http://testhtml5.vulnweb.com',
    audit:  {
        elements: [:links, :forms, :cookies]
    },
    checks: 'active/*'
)

while instance.busy?
    ap instance.proxy.progress
    sleep 1
end

instance.shutdown
